name: Test Self-Hosted Runner

on:
  push:
    branches: [ main ]  # or change to your default branch

jobs:
  hello-job:
    runs-on: self-hosted

    steps:
      - name: Print Hello
        run: echo "Hello from self-hosted runner!"
